import {Store} from './store';

export const AmazonEs: Store = {
  backoffStatusCodes: [403, 429, 503],
  currency: '€',
  labels: {
    captcha: {
      container: 'body',
      text: ['introduzca los caracteres que ve a continuación'],
    },
    inStock: {
      container: '#desktop_buybox',
      text: ['añadir a la cesta'],
    },
    maxPrice: {
      container: '#priceblock_ourprice',
    },
    outOfStock: [
      {
        container: '#availability',
        text: ['No disponible'],
      },
    ],
  },
  links: [
    {
      brand: 'test:brand',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B07PW9VBK5&Quantity.1=1',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.amazon.es/dp/B07PW9VBK5',
    },
    {
      brand: 'msi',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HM4V2DH&Quantity.1=1',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HM4V2DH',
    },
    {
      brand: 'evga',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HGYXP4C&Quantity.1=1',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HGYXP4C',
    },
    {
      brand: 'evga',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HJ9XFNM&Quantity.1=1',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HJ9XFNM',
    },
    {
      brand: 'evga',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HGBYWQ6&Quantity.1=1',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HGBYWQ6',
    },
    {
      brand: 'evga',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HGLN78Q&Quantity.1=1',
      model: 'xc3',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HGLN78Q',
    },
    {
      brand: 'evga',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HH1BMQQ&Quantity.1=1',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HH1BMQQ',
    },
    {
      brand: 'gigabyte',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HLZXHZY&Quantity.1=1',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HLZXHZY',
    },
    {
      brand: 'gigabyte',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HHZVZ3N&Quantity.1=1',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HHZVZ3N',
    },
    {
      brand: 'asus',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HN37VQK&Quantity.1=1',
      model: 'tuf',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HN37VQK',
    },
    {
      brand: 'asus',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HN4DSTC&Quantity.1=1',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HN4DSTC',
    },
    {
      brand: 'asus',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HN6KYS3&Quantity.1=1',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HN6KYS3',
    },
    {
      brand: 'msi',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HM4M621&Quantity.1=1',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HM4M621',
    },
    {
      brand: 'zotac',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08HR1NPPQ&Quantity.1=1',
      model: 'trinity',
      series: '3080',
      url: 'https://www.amazon.es/dp/B08HR1NPPQ',
    },
    {
      brand: 'asus',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08R3TZHMB&Quantity.1=1',
      model: 'trinity',
      series: '3060ti',
      url: 'https://www.amazon.es/dp/B08R3TZHMB',
    },
        {
      brand: 'gigabyte',
      cartUrl:
        'https://www.amazon.es/gp/aws/cart/add.html?ASIN.1=B08KHL21CV&Quantity.1=1',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.amazon.es/dp/B08KHL21CV',
    },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ASUS-DisplayPort-rodamientos-ventilador-certificaci%C3%B3n/dp/B08HHDP9DW?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Tarjeta-ASUS-DisplayPort-Axial-tech-2-9-Slot/dp/B08J6GMWCQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-10G-P5-3883-KR-Cooling-Backplate/dp/B08HGLN78Q?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-10G-P5-3895-KR-Technology-Backplate/dp/B08HGBYWQ6?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-24G-P5-3973-KR-Cooling-Backplate/dp/B08HGZ4XSZ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-10G-P5-3897-KR-Technology-Backplate/dp/B08HGYXP4C?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-Gaming-10G-P5-3881-KR-Cooling/dp/B08HH1BMQQ?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-3070-BLACK-GAMING/dp/B08L3QCZKZ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-10G-P5-3885-KR-Cooling-Backplate/dp/B08HJ9XFNM?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-08G-P5-3753-KR-Cooling-Backplate/dp/B08L3QZP7W?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-08G-P5-3755-KR-Cooling-Backplate/dp/B08L3Q41SM?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-24G-P5-3975-KR-Cooling-Backplate/dp/B08HGTNDL4?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-24G-P5-3987-KR-Technology-Backplate/dp/B08HGS1SXH?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-Gaming-24G-P5-3971-KR-Cooling/dp/B08HGKQ527?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-24G-P5-3985-KR-Technology-Backplate/dp/B08HGFNPJQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-10G-P5-3897-KR-GeForce-Technology-met%C3%A1lica/dp/B08HR3Y5GQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-24G-P5-3985-KR-GeForce-tecnolog%C3%ADa-Trasera/dp/B08J5NMDP7?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/EVGA-GeForce-tecnolog%C3%ADa-Posterior-24G-P5-3987-KR/dp/B08J5F3G18?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GV-N3090EAGLE-OC-24GD-Tarjeta-gr%C3%A1fica/dp/B08HHZSQVF?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GV-N3080GAMING-OC-10GD-Tarjeta-gr%C3%A1fica/dp/B08HLZXHZY?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GV-N3080EAGLE-OC-10GD-Tarjeta-gr%C3%A1fica/dp/B08HHZVZ3N?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GeForce-Vision-Tarjeta-gr%C3%A1fica/dp/B08KH7RL89?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-Technology-AORUS-GeForce-Master/dp/B08KHLDS72?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-Technology-GeForce-Tarjeta-GV-N3090TURBO-24GD/dp/B08KHKDTSJ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-AORUS-GeForce-3090-Master/dp/B08KH7R4FQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-RTX-3070-Eagle-OC/dp/B08KHL2J5X?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-RTX-3070-Gaming-OC/dp/B08KHL21CV?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GV-N3090GAMING-OC-24GD-Tarjeta-gr%C3%A1fica/dp/B08HLYQ9XL?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-AORUS-GeForce-3090-Xtreme/dp/B08KHJS572?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/GIGABYTE-GeForce-refrigeraci%C3%B3n-GV-N3080AORUS-M-10GD/dp/B08KJ3VKLQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/GIGABYTE-Ventiladores-WINDFORCE-GV-N3080GAMING-OC-10GD/dp/B08HJTH61J?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-Ventiladores-WINDFORCE-GV-N3090EAGLE-OC-24GD/dp/B08HJPDJTY?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GeForce-Vision-Tarjeta-gr%C3%A1fica/dp/B08MDC8J27?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GeForce-Eagle-Tarjeta-gr%C3%A1fica/dp/B08ML7QVF5?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-GeForce-RTX-3070-Vision/dp/B08LNWPYRS?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/INNO3D-GeForce-RTX-3080-Twin/dp/B08JD6QPXD?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/INNO3D-RTX-3080-iCHILL-X3/dp/B08JF9VD3N?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/INNO3D-RTX-3080-iCHILL-X4/dp/B08JFJFL9J?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/KFA2-GeForce-Serious-PCI-Express-Tarjeta/dp/B08JCPQG97?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-RTX-3090-Ventus-24G/dp/B08HM661YM?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Msi-Rtx-3090-Gaming-Trio/dp/B08HM6D7TM?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Msi-Rtx-3080-Ventus-10G/dp/B08HM4M621?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Msi-Rtx-3080-Gaming-Trio/dp/B08HM4V2DH?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/GeForce-RTX-3070-Ventus-Enthusiast/dp/B08L6PCZTR?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-RTX-3070-VENTUS/dp/B08LNQTSCT?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-3070-Gaming-Trio/dp/B08LNPPCWJ?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-384-Bit-Tri-Frozr-Architecture/dp/B08HRBW6VB?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-320-Bit-Tri-Frozr-Architecture/dp/B08HR7SV3M?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-RTX-3090-24G/dp/B08HR9D2JS?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/NVIDIA-GeForce-RTX-3090-Founders/dp/B08HR6ZBYJ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Palit-GeForce-RTX-3080-GamingPro/dp/B08JCVWTQY?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Palit-GamingPro-Ray-Tracing-DisplayPort-Advanced/dp/B08JCKYYL8?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Palit-GamingPro-DisplayPort-Advanced-TurboFan/dp/B08JQQ1VD1?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Palit-GeForce-RTX-3070-GamingPro/dp/B08LDS72P2?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08HBJB7YD?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/PNY-Tarjeta-Gr%C3%A1fica-GeForce-Uprising/dp/B08HBTJMLJ?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/PNY-Tarjeta-Gr%C3%A1fica-GeForce-Gaming/dp/B08HBR7QBM?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/PNY-Tarjeta-Gr%C3%A1fica-GeForce-Gaming/dp/B08HBQWBHH?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/GeForce-RTXTM-3090-24GB-XLR8/dp/B08HBVX53D?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/PNY-VCG30708DFMPB-Tarjeta-Gr%C3%A1fica-Uprising/dp/B08HBF5L3K?ref_=ast_sto_dp&th=1&psc=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-Tarjeta-gr%C3%A1fica-GEFORCE-ZT-A30900D-10P/dp/B08HR9JSMS?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-Tarjeta-gr%C3%A1fica-GEFORCE-ZT-A30700E-10P/dp/B08HRBR7K9?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Tarjeta-gr%C3%A1fica-GEFORCE-RTX-3080/dp/B08HR1NPPQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZT-A30800F-10P-Tarjeta-gr%C3%A1fica-NVIDIA-GeForce/dp/B08KGVL9JQ?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-GeForce-3080-Extreme-Holo/dp/B08KFGS91R?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-IceStorm-Advanced-Lighting-ZT-A30800J-10P/dp/B08HVV2P4Z?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-IceStorm-Advanced-Lighting-ZT-A30800D-10P/dp/B08HJNKT3P?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-3080-AMP-HOLO-GDDRX/dp/B08PC6N5LB?ref_=ast_sto_dp',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08NW693LG?th=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08NW5HNYW?th=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08HBJB7YD?th=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08HBF5L3K?th=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08HBR7QBM?th=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/RTX-3070-Gaming-Triple-CTLR/dp/B08HBR7QBM?th=1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ASUS-Strix-NVIDIA-GeForce-3070/dp/B08NB3DQVK',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-256-Bit-Tri-Frozr-Architecture/dp/B08KWN2LZG',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ASUS-Strix-NVIDIA-GeForce-3070/dp/B08N9VTCWG',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/MSI-GeForce-3070-SUPRIM-PCI/dp/B08P37HYZM',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ZOTAC-IceStorm-refrigeraci%C3%B3n-iluminaci%C3%B3n-ZT-A30700H-10P/dp/B08LF1CWT2',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Zotac-GeForce-3070-Holo-NVIDIA/dp/B08R427DMQ',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Asus-DUAL-RTX3070-8G-DisplayPort-Ventiladores-Axial-Tech/dp/B08HSJ1622',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-AORUS-GeForce-3070-Master/dp/B08LNY8P5L',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ASUS-TUF-RTX3070-O8G-GAMING-Tarjeta-DisplayPort-rodamiento/dp/B08LLG9KQT',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Asus-DUAL-RTX3070-O8G-DisplayPort-Ventiladores-Axial-Tech/dp/B08KHFZN9P',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Asus-DUAL-RTX3070-O8G-DisplayPort-Ventiladores-Axial-Tech/dp/B08KHFZN9P',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/ASUS-TUF-RTX3070-O8G-GAMING-Tarjeta-DisplayPort-rodamiento/dp/B08LLG9KQT',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Gigabyte-Tarjeta-Ventiladores-WINDFORCE-GV-N3070EAGLE-8GD/dp/B08KXZV626',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Tarjeta-gr%C3%A1fica-ZOTAC-Gaming-GEFORCE/dp/B08LBVNKT1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/GIGABYTE-Ventiladores-WINDFORCE-GV-N3070VISION-OC-8GD/dp/B08M13DXSZ',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.es/Palit-GeForce-RTX-3070-GameRock/dp/B08NT9WQBG',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.amazon.com/-/es/GeForce-RTX-3070-Architecture-OC/dp/B08KWPDXJZ',     },
  ],
  name: 'amazon-es',
};
