  import {Store} from './store';

export const Electronicamente: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.sistock',
      text: ['en stock'],
    },
    outOfStock: {
      container: '.nostock',
      text: ['Producto sujeto'],
    },
  },
  links: [
{       brand: 'asus',       model: 'strix oc',            series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34247-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-oc-rog-strix-gaming-10gb-ddr6-3xdp-2xhdmi-90yv0fa1-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'gaming oc',           series: '3060ti',     url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34923-tarjeta-grafica-pcie-nvidia-gf-rtx-3060-ti-gaming-oc-8gb-ddr6-2xdp-2xhdmi-gv-n306tgaming-oc-8g.html?search_query=rtx&results=79',     },
{       brand: 'asus',       model: 'strix',               series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34249-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-rog-strix-gaming-10gb-ddr6-3xdp-2xhdmi-90yv0fa0-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/29129-tarjeta-grafica-pcie-nvidia-gf-rtx-2060-oc-6gb-ddr6-3xdp-hdmi-gvn2060o6-00-g2.html?search_query=rtx&results=79',     },
{       brand: 'zotac',      model: 'trinity',             series: '3090',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34167-tarjeta-grafica-pcie-nvidia-gf-rtx-3090-trinity-24gb-ddr6-3xdp-hdmi-zt-a30900d-10p.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'aorus xtreme',        series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34883-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-xtrem-10gb-ddr6-3xdp-3xhdmi-gv-n3080aorus-x-10gd.html?search_query=rtx&results=79',     },
{       brand: 'pny',        model: 'xlr8 revel',          series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34245-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-gaming-10gb-ddr6-3xdp-hdmi-vcg308010tfxppb.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'gaming',              series: '3090',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34166-tarjeta-grafica-pcie-nvidia-gf-rtx-3090-gaming-24gb-ddr6-3xdp-2xhdmi-gvn3090go-00-g.html?search_query=rtx&results=79',     },
{       brand: 'asus',       model: 'tuf',                 series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34250-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-tuf-gaming-10gb-ddr6-3xdp-2xhdmi-90yv0fb0-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'pny',        model: 'xlr8 revel',          series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34246-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-gaming-10gb-ddr6-4xdp-vcg308010tfxmpb.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'aorus master',        series: '3090',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34875-tarjeta-grafica-pcie-nvidia-gf-rtx-3090-master-24gb-ddr6-3xdp-3xhdmi-gv-n3090aorus-m-24gd.html?search_query=rtx&results=79',     },
{       brand: 'asus',       model: 'tuf oc',              series: '3080',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34248-tarjeta-grafica-pcie-nvidia-gf-rtx-3080-oc-tuf-gaming-10gb-ddr6-3xdp-2xhdmi-90yv0fb1-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'aorus master',        series: '3070',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34874-tarjeta-grafica-pcie-nvidia-gf-rtx-3070-master-8gb-ddr6-3xdp-3xhdmi-gv-n3070aorus-m-8gd.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'gaming oc',           series: '3070',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34853-tarjeta-grafica-pcie-nvidia-gf-rtx-3070-gaming-oc-8gb-ddr6-2xdp-2xhdmi-gv-n3070gaming-oc-8g.html?search_query=rtx&results=79',     },
{       brand: 'asus',       model: 'strix',               series: '3090',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34165-tarjeta-grafica-pcie-nvidia-gf-rtx-3090-24gb-ddr6-3xdp-2xhdmi-90yv0f93-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'msi',        model: 'ventus 2x oc',        series: '3070',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/35402-tarjeta-grafica-pcie-nvidia-gf-rtx-3070-ventus-2x-oc-8gb-ddr6-hdmi-3xdp-912-v390-008.html?search_query=rtx&results=79',     },
{       brand: 'evga',       model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/29089-tarjeta-grafica-pcie-nvidia-gf-rtx-2070-8gb-ddr6-3xdp-hdmi-08g-p4-2173-kr.html?search_query=rtx&results=79',     },
{       brand: 'asus',       model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/29837-tarjeta-grafica-pcie-nvidia-gf-rtx-2070-strix-gaming-8gb-ddr6-2xhdmi-2xdp-90yv0c92-m0na00.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/30346-tarjeta-grafica-pcie-nvidia-gf-rtx-2080-dual-8gb-ddr6-hdmi-3xdp-usb-c-90yv0c33-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/31656-tarjeta-grafica-pcie-nvidia-gf-rtx-2080-ti-11gb-ddr6-hdmi-3xdp-usb-c-90yv0c42-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/32112-tarjeta-grafica-pcie-nvidia-gf-rtx-2080-ti-turbo-11gb-ddr6-hdmi-2xdp-usb-c-90yv0c40-m0nm00.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/32826-tarjeta-grafica-pcie-nvidia-gf-rtx-2060-oc-6gb-ddr6-dp-2xhdmi-dvi-90yv0cj1-m0na00.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/32825-tarjeta-grafica-pcie-nvidia-gf-rtx-2060-6gb-ddr6-dp-2xhdmi-dvi-90yv0cj0-m0na00.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/32791-tarjeta-grafica-pcie-nvidia-gf-rtx-2060-oc-6gb-ddr6-3xdp-hdmi-gv-n2060oc-6gd.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/33345-tarjeta-grafica-pcie-nvidia-gf-rtx-2070-superwindforce-oc-8gb-ddr6-3xdp-hdmi-gv-n207swf3oc-8gd.html?search_query=rtx&results=79',     },
{       brand: 'nvidia',     model: 'founders edition',    series: '3060',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34081-tarjeta-grafica-pcie-nvidia-gf-rtx-2060-evo-gaming-6gb-ddr6-dp-hdmi-90yv0d21-m0na00.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'gaming oc',           series: '3060ti',     url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34837-tarjeta-grafica-pcie-nvidia-gf-rtx-3060-ti-gaming-oc-pro-8gb-ddr6-2xdp-2xhdmi-gv-n306tgamingocpro8.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'vision oc',           series: '3070',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34924-tarjeta-grafica-pcie-nvidia-gf-rtx-3070-vision-oc-8gb-ddr6-2xdp-2xhdmi-gv-n3070vision-oc-8g.html?search_query=rtx&results=79',     },
{       brand: 'gigabyte',   model: 'eagle oc',            series: '3060ti',     url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/34882-tarjeta-grafica-pcie-nvidia-gf-rtx-3060-ti-eagle-oc-8gb-ddr6-2xdp-2xhdmi-gv-n306teagle-oc-8gd.html?search_query=rtx&results=79',     },
{       brand: 'msi',        model: 'ventus 3x',           series: '3070',       url:         'https://www.electronicamente.com/comprar-tarjetas-graficas/35403-tarjeta-grafica-pcie-nvidia-gf-rtx-3070-ventus-3x-8gb-ddr6-hdmi-3xdp-912-v390-007.html?search_query=rtx&results=79',     },
	  ],
  name: 'electronicamente',
};