import {Store} from './store';

export const Ldlc: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.qty-selector',
      text: ['Cantidad'],
    },
    outOfStock: {
      container: '.product-info',
      text: ['Avísame', 'Crea un PC con este producto'],
    },
  },
  links: [
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00391682.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00390466.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00375431.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00391624.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369094.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385535.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369299.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00398046.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00376208.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386334.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368574.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369265.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00375625.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00398045.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368844.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368506.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369303.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368690.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386063.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00376207.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369298.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00375448.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00390727.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369268.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368692.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386332.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368968.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369150.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00375644.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369158.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368579.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368931.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368691.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00368789.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00369072.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00400753.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385044.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00401655.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385129.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00395874.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386904.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385128.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385048.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386907.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00401469.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385131.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385045.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00384232.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385465.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385462.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394365.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385046.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394151.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386925.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385043.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386926.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00384189.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385127.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00384225.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386023.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385132.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385463.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00408781.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386927.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00383541.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386014.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385126.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00383549.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00400752.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00384198.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394150.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385466.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00385663.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00408780.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386030.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394604.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00393364.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00386928.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00395231.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00393363.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00408782.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394596.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394600.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394363.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394595.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394436.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394589.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394060.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00393739.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394379.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394357.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394507.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394343.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394602.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394375.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00400751.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394373.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394590.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394607.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394053.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394434.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394608.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00394586.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00398042.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00279909.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00280144.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00398031.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00281801.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00279892.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00279968.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00345085.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00345087.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00347350.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00280293.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00280302.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00280137.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00404597.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00279970.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.ldlc.com/es-es/ficha/PB00280298.html',     },
  ],
  name: 'ldlc',
};
