  import {Store} from './store';

export const Pcbox: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.product-actions',
      text: ['AÑADIR A LA CESTA'],
    },
    outOfStock: {
      container: '.product-actions',
      text: ['Añadir a Wishlist'],
    },
  },
  links: [
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1697/tarjeta-grafica-24gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1683/tarjeta-grafica-24gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1705/tarjeta-grafica-24gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1682/tarjeta-grafica-24gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg189/tarjeta-grafica-11gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1681/tarjeta-grafica-24gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi1671/tarjeta-grafica-11gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/zot156/tarjeta-grafica-24gb-zotac-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg188/tarjeta-grafica-11gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5451/tarjeta-grafica-11gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg191/tarjeta-grafica-8gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1687/tarjeta-grafica-10gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2304/tarjeta-grafica-10gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1655/tarjeta-grafica-10gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1676/tarjeta-grafica-10gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1590/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg190/tarjeta-grafica-8gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1588/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5526/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1423/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5557/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1536/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1505/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5627/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5833/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2245/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gain7/tarjeta-grafica-8gb-gainward-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2264/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1704/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/pal72/tarjeta-grafica-8gb-palit-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2062/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1571/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1670/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5455/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5540/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/pny234/tarjeta-grafica-6gb-pny-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1635/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5609/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1432/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1406/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi1983/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1694/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2229/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1392/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5703/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2077/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg150/tarjeta-grafica-8gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1254/tarjeta-grafica-6gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2019/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5518/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1712/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1375/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1396/tarjeta-grafica-8gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5260/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2422/tarjeta-grafica-8gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5625/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5683/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5872/tarjeta-grafica-8gb-amd-asus',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg210/tarjeta-grafica-6gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/pal70/tarjeta-grafica-8gb-palit-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5528/tarjeta-grafica-8gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1252/tarjeta-grafica-6gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2251/tarjeta-grafica-6gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5288/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1253/tarjeta-grafica-6gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5263/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5485/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1442/tarjeta-grafica-6gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5456/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/evg94/tarjeta-grafica-3gb-evga-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5619/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi1827/tarjeta-grafica-6gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5475/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5696/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5564/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5633/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5581/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5604/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2152/tarjeta-grafica-6gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5628/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1533/tarjeta-grafica-6gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5458/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5716/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5303/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5524/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/ask5301/tarjeta-grafica-6gb-asus-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi1836/tarjeta-grafica-6gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/gby1294/tarjeta-grafica-6gb-gigabyte-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi2234/tarjeta-grafica-6gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://www.pcbox.com/productos/msi1838/tarjeta-grafica-6gb-msi-geforce',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         '',     },
	  ],
  name: 'pcbox',
};
