import 		{Store} from './store';

export const PCComponentes: Store = 		{
  currency: '€',
  labels: 		{
    inStock: 		{
      container: '#btnsWishAddBuy',
      text: ['Comprar'],
    },
    maxPrice: 		{
      container: '#precio-main',
      euroFormat: true,
    },
    outOfStock: 		{
      container: '#btnsWishAddBuy',
      text: ['Avísame'],
    },
  },
  links: [
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-geforce-rtx-3080-10g-gaming-oc-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-tuf-geforce-rtx-3060ti-o8g-gaming-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-xc3-black-gaming-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-xc3-gaming-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3080-ventus-3x-oc-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-rtx-3060-ti-gaming-x-trio-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3080-xlr8-gaming-epic-x-rgb-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-geforce-rtx-3060-ti-d6-twin-edge-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-gaming-oc-10g-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-vision-oc-10gb-gddr6x-recondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3060ti-xlr8-gaming-revel-epic-x-rgb-edition-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-trinity-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-trinity-oc-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-geforce-rtx-3060ti-d6-twin-edge-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-ekwb-geforce-rtx-3070-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3070-uprising-dual-fan-edition-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-gaming-geforce-rtx-3070-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-tuf-gaming-geforce-rtx-3070-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-white-edition-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3070-master-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-vision-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3070-xc3-ultra-gaming-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-gaming-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3070-xlr8-gaming-revel-epic-x-rgb-triple-fan-edition-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-eagle-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-gaming-x-trio-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3070-xc3-black-gaming-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-geforce-rtx-3070-dual-oc-edition-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-geforce-rtx-3070-dual-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-suprim-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-eagle-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3070-twin-edge-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3060-ti-vision-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-geforce-rtx-3060-oc-edition-12gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3060-gaming-x-12gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3060-ti-ftw3-ultra-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3080-master-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-amp-holo-10gb-gddrx6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3080-xtreme-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3080-suprim-x-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-geforce-rtx-3060ti-dual-o8g-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-tuf-geforce-rtx-3080-oc-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3060-ti-xc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3060-ti-master-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3080-xtreme-waterforce-wb-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3060-ti-eagle-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3060-ti-gaming-oc-pro-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-eagle-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-eagle-oc-10g-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3060-ti-gaming-x-trio-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3080-gaming-x-trio-10gb-gddr6x-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-rtx-3060-ti-ventus-2x-oc-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-geforce-rtx-3060ti-o8g-gaming-8gb-gddr6-reacondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-turbo-10gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-geforce-rtx-3080-10g-gaming-oc-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-tuf-geforce-rtx-3060ti-o8g-gaming-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-xc3-black-gaming-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-xc3-gaming-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3080-ventus-3x-oc-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-rtx-3060-ti-gaming-x-trio-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3080-xlr8-gaming-epic-x-rgb-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-geforce-rtx-3060-ti-d6-twin-edge-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-gaming-oc-10g-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-vision-oc-10gb-gddr6x-recondicionado',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3060ti-xlr8-gaming-revel-epic-x-rgb-edition-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-trinity-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-trinity-oc-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-geforce-rtx-3060ti-d6-twin-edge-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-ekwb-geforce-rtx-3070-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3070-uprising-dual-fan-edition-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-gaming-geforce-rtx-3070-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-tuf-gaming-geforce-rtx-3070-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-white-edition-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3070-master-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-vision-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3070-xc3-ultra-gaming-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-gaming-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/pny-geforce-rtx-3070-xlr8-gaming-revel-epic-x-rgb-triple-fan-edition-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-eagle-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-gaming-x-trio-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3070-xc3-black-gaming-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-geforce-rtx-3070-dual-oc-edition-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-geforce-rtx-3070-dual-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3070-suprim-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3070-eagle-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3070-twin-edge-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3060-ti-vision-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-geforce-rtx-3060-oc-edition-12gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3060-gaming-x-12gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3060-ti-ftw3-ultra-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3080-master-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-amp-holo-10gb-gddrx6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3080-xtreme-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3080-suprim-x-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-geforce-rtx-3060ti-dual-o8g-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-tuf-geforce-rtx-3080-oc-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/evga-geforce-rtx-3060-ti-xc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3060-ti-master-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-aorus-geforce-rtx-3080-xtreme-waterforce-wb-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3060-ti-eagle-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3060-ti-gaming-oc-pro-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-eagle-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-eagle-oc-10g-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3060-ti-gaming-x-trio-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-geforce-rtx-3080-gaming-x-trio-10gb-gddr6x',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/msi-rtx-3060-ti-ventus-2x-oc-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/asus-rog-strix-geforce-rtx-3060ti-o8g-gaming-8gb-gddr6',     },
{       brand: 'msi',       model: 'ventus 3x oc',       series: '3080',       url:         'https://www.pccomponentes.com/gigabyte-geforce-rtx-3080-turbo-10gb-gddr6',     },
  ],
  name: 'pccomponentes',
};
