  import {Store} from './store';

export const Updigital: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.product-availability',
      text: ['Últimas unidades', 'Si tiene alguna duda'],
    },
    outOfStock: {
      container: '.product-availability',
      text: ['No hay suficientes productos en stock'],
    },
  },
  links: [
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-PNY-VGA-NVIDIA-RTX-3090-24GB-XLR8-Gaming-UPRISING{-:ean1343181-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3090-SUPRIM-X-24G-DDR6X{-:ean1342563-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-W24-DDR6X{-:ean1336314-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-WB24-DDR6{-:ean1339031-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-GAMING-OC-24G-DDR6X{-:ean1331702-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-TURBO-24GB-DDR6X{-:ean1339032-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-MASTER24G-DDR6X{-:ean1332864-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-24G-DDR6X{-:ean1333891-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-VISION-24G-DDR6X{-:ean1334605-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-EAGLE-OC-24G-DDR6X{-:ean1331703-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-EAGLE-24G-DDR6X{-:ean1333892-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3090-GAMING-X-TRIO-24G{-:ean1331633-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-GAMING-X-TRIO-10G{-:ean1331461-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-W-10G{-:ean1335379-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-WB-10G{-:ean1335378-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-MASTER10G-DDR6X{-:ean1339935-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-GAMING-OC-10G-DDR6X{-:ean1331426-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-VISION-OC-10G-DDR6X{-:ean1333678-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-10G-DDR6X{-:ean1332907-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3070-MASTER-8G-DDR6{-:ean1334013-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-EAGLE-10G-DDR6X{-:ean1335411-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-EAGLE-OC-10G-DDR6X{-:ean1331425-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-GAMING-X-TRIO-8GB{-:ean1333728-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-SUPRIM-X-10G-DDR6X{-:ean1335484-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-VENTUS-2X-OC-8GB{-:ean1333730-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-VENTUS-3X-OC-8GB{-:ean1333729-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-GAMING-OC-8G-DDR6{-:ean1333606-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-VENTUS-3X-10G-OC{-:ean1331354-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-VISION-OC-8G-DDR6{-:ean1333607-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-VENTUS-2X-OC-8G-DDR6{-:ean1335561-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-EAGLE-OC-8G-DDR6{-:ean1333605-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-EAGLE-8G-DDR6{-:ean1333679-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3060-Ti-Maste-8-DDR6{-:ean1335555-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-VENTUS-3X-OC-8G-DDR6{-:ean1336237-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-Gaming-OC-PRO-8GB{-:ean1340184-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-VISION-OC-8GB-DDR6{-:ean1341031-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-Gaming-OC-8GB-DDR6{-:ean1335557-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-GAMING-X-12GB{-:ean1342215-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-E-VGA-NVIDIA-RTX-3060-12GB-DDR6{-:ean1342348-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-VENTUS-3X-12G-OC{-:ean1342216-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-VISION-OC-12GB-DDR6{-:ean1341549-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-EAGLE-OC-8G-DDR6{-:ean1335556-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-GAMING-OC-12GB-DDR6{-:ean1341548-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-GAMING-X-TRIO-12GB{-:ean1341547-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-EAGLE-OC-12G-DDR6{-:ean1341550-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-EAGLE-12G-DDR6{-:ean1341597-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-EAGLE-8G-DDR6{-:ean1335558-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-AERO-ITX-12G-OC{-:ean1342217-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-GAMING-X-TRIO-8G-DDR6{-:ean1335560-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-GTX-1660-SUPER-OC-6G-DDR6{-:ean136620-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-GTX-1660-SUPER-6G-DDR6{-:ean1343335-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-GTX-1660-SUPER-AERO-ITX-OC-DDR6{-:ean136714-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-GTX-1660-SUPER-VENTUS-XS-6G-OC-DDR6{-:ean138242-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-PNY-VGA-NVIDIA-RTX-3090-24GB-XLR8-Gaming-UPRISING{-:ean1343181-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3090-SUPRIM-X-24G-DDR6X{-:ean1342563-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-W24-DDR6X{-:ean1336314-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-WB24-DDR6{-:ean1339031-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-GAMING-OC-24G-DDR6X{-:ean1331702-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-TURBO-24GB-DDR6X{-:ean1339032-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-MASTER24G-DDR6X{-:ean1332864-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-24G-DDR6X{-:ean1333891-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-VISION-24G-DDR6X{-:ean1334605-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-EAGLE-OC-24G-DDR6X{-:ean1331703-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-EAGLE-24G-DDR6X{-:ean1333892-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3090-GAMING-X-TRIO-24G{-:ean1331633-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-GAMING-X-TRIO-10G{-:ean1331461-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-W-10G{-:ean1335379-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-WB-10G{-:ean1335378-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-MASTER10G-DDR6X{-:ean1339935-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-GAMING-OC-10G-DDR6X{-:ean1331426-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-VISION-OC-10G-DDR6X{-:ean1333678-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-10G-DDR6X{-:ean1332907-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3070-MASTER-8G-DDR6{-:ean1334013-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-EAGLE-10G-DDR6X{-:ean1335411-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-EAGLE-OC-10G-DDR6X{-:ean1331425-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-GAMING-X-TRIO-8GB{-:ean1333728-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-SUPRIM-X-10G-DDR6X{-:ean1335484-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-VENTUS-2X-OC-8GB{-:ean1333730-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-VENTUS-3X-OC-8GB{-:ean1333729-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-GAMING-OC-8G-DDR6{-:ean1333606-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-VENTUS-3X-10G-OC{-:ean1331354-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-VISION-OC-8G-DDR6{-:ean1333607-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-VENTUS-2X-OC-8G-DDR6{-:ean1335561-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-EAGLE-OC-8G-DDR6{-:ean1333605-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-EAGLE-8G-DDR6{-:ean1333679-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3060-Ti-Maste-8-DDR6{-:ean1335555-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-VENTUS-3X-OC-8G-DDR6{-:ean1336237-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-Gaming-OC-PRO-8GB{-:ean1340184-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-VISION-OC-8GB-DDR6{-:ean1341031-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-Gaming-OC-8GB-DDR6{-:ean1335557-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-GAMING-X-12GB{-:ean1342215-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-E-VGA-NVIDIA-RTX-3060-12GB-DDR6{-:ean1342348-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-VENTUS-3X-12G-OC{-:ean1342216-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-VISION-OC-12GB-DDR6{-:ean1341549-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-EAGLE-OC-8G-DDR6{-:ean1335556-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-GAMING-OC-12GB-DDR6{-:ean1341548-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-GAMING-X-TRIO-12GB{-:ean1341547-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-EAGLE-OC-12G-DDR6{-:ean1341550-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-EAGLE-12G-DDR6{-:ean1341597-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-EAGLE-8G-DDR6{-:ean1335558-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-AERO-ITX-12G-OC{-:ean1342217-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-GAMING-X-TRIO-8G-DDR6{-:ean1335560-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-GTX-1660-SUPER-OC-6G-DDR6{-:ean136620-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-GTX-1660-SUPER-6G-DDR6{-:ean1343335-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-GTX-1660-SUPER-AERO-ITX-OC-DDR6{-:ean136714-.html',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-GTX-1660-SUPER-VENTUS-XS-6G-OC-DDR6{-:ean138242-.html',     },
  
  ],
  name: 'updigital',
};
