  import {Store} from './store';

export const Updigital: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.product-availability',
      text: ['Últimas unidades', 'Si tiene alguna duda'],
    },
    outOfStock: {
      container: '.product-availability',
      text: ['No hay suficientes productos en stock'],
    },
  },
  links: [
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-W24-DDR6X{-:ean1336314-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-XTREM-WB24-DDR6{-:ean1339031-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-PNY-QUADRO-RTX-5000-16GB-GDDR6X{-:ean136737-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-TURBO-24GB-DDR6X{-:ean1339032-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3090-MASTER24G-DDR6X{-:ean1332864-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-GAMING-OC-24G-DDR6X{-:ean1331702-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-VISION-24G-DDR6X{-:ean1334605-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-EAGLE-OC-24G-DDR6X{-:ean1331703-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3090-EAGLE-24G-DDR6X{-:ean1333892-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-AMD-RADEON-RX-6900-XT-MASTER-16{-:ean1342278-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-W-10G{-:ean1335379-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-XTREM-WB-10G{-:ean1335378-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-GAMING-OC-10G-DDR6X{-:ean1331426-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3080-MASTER10G-DDR6X{-:ean1339935-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-PNY-QUADRO-RTX-4000-8GB-GDDR6X{-:ean1336117-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-EAGLE-10G-DDR6X{-:ean1335411-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-VISION-OC-10G-DDR6X{-:ean1333678-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-GAMING-X-TRIO-8GB{-:ean1333728-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3080-EAGLE-OC-10G-DDR6X{-:ean1331425-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3080-SUPRIM-X-10G-DDR6X{-:ean1335484-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-VENTUS-2X-OC-8GB{-:ean1333730-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3070-MASTER-8G-DDR6{-:ean1334013-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-GAMING-OC-8G-DDR6{-:ean1333606-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-VISION-OC-8G-DDR6{-:ean1333607-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-AMD-RADEON-RX-6700-XT-12G-DDR6{-:ean1342277-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-AMD-RADEON-RX-6700-XT-EAGLE-12G-DDR6{-:ean1342349-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3070-VENTUS-3X-OC-8GB{-:ean1333729-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-VENTUS-2X-OC-8G-DDR6{-:ean1335561-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-EAGLE-OC-8G-DDR6{-:ean1333605-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3070-EAGLE-8G-DDR6{-:ean1333679-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-VGA-NVIDIA-RTX-3060-Ti-Maste-8-DDR6{-:ean1335555-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-VENTUS-3X-OC-8G-DDR6{-:ean1336237-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-Gaming-OC-PRO-8GB{-:ean1340184-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-VISION-OC-8GB-DDR6{-:ean1341031-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-Gaming-OC-8GB-DDR6{-:ean1335557-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-GAMING-X-12GB{-:ean1342215-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-Aorus-E-VGA-NVIDIA-RTX-3060-12GB-DDR6{-:ean1342348-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-VENTUS-3X-12G-OC{-:ean1342216-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-EAGLE-OC-8G-DDR6{-:ean1335556-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-GAMING-OC-12GB-DDR6{-:ean1341548-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-VISION-OC-12GB-DDR6{-:ean1341549-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-GAMING-X-TRIO-12GB{-:ean1341547-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-POWERCOLOR-RED-DRAGON-RX-5700XT-OC-8GB-GDD{-:ean1326869-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-ROG-STRIX-RX-5700XT-O8G-GAMING{-:ean1322480-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-POWERCOLOR-RED-DEVIL-RX-5700XT-OC-8GB-GDDR{-:ean1326868-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-EAGLE-OC-12G-DDR6{-:ean1341550-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-EAGLE-12G-DDR6{-:ean1341597-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-RTX-3060-Ti-EAGLE-8G-DDR6{-:ean1335558-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-AERO-ITX-12G-OC{-:ean1342217-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-RTX-3060-Ti-GAMING-X-TRIO-8G-DDR6{-:ean1335560-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-POWERCOLOR-RX-5700XT-8GB-GDDR6{-:ean1326870-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-GTX-1660-SUPER-ROG-STRIX-OC-6GB-GDDR6{-:ean136575-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-ROG-STRIX-GTX-1660-SUPER-ADVAN-GAM-{-:ean1339628-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-GTX-1660-SUPER-VENTUS-XS-6G-OC-DDR6{-:ean138242-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-MSI-GTX-1660-SUPER-VENTUS-XS-OC-6GB-GDDR6{-:ean136708-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-POWERCOLOR-RX-5600XT-OC-6GB-GDDR6{-:ean1326873-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-ROG-STRIX-GTX-1660-SUPER-GAMING-6GB-G{-:ean1333406-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-MSI-RX580-ARMOR-8GB-OC-GDDR5{-:ean136657-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-Gigabyte-VGA-NVIDIA-GTX-1660-SUPER-GAMING-OC-6G{-:ean138234-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-MSI-VGA-NVIDIA-GTX-1660-Ti-VENTUS-6GB-OC-DDR6{-:ean1334925-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-TUF-GTX-1660-SUPER-OC-GAMING-6GB-GDDD{-:ean1327845-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-GIGABYTE-GTX-1660-SUPER-6GB-GDDR6-10{-:ean136620-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-TUF-GTX-1660-SUPER-GAMING-6GB-GDDR6{-:ean1320455-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-MSI-GTX-1660-SUPER-GAMING-X-6GB-GDDR6{-:ean136705-.html',     },
{       brand: 'nvidia',       model: 'founders edition',       series: '3060ti',       url:         'https://updigital-almeria.es/tarjetas-graficas-pci-e/-TARJETA-GRFICA-ASUS-PHOENIX-GTX-1660-SUPER-OC-6GB-GDDR6{-:ean136490-.html',     },
	  ],
  name: 'updigital',
};