import {Store} from './store';

export const VsGamers: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '#vs-product-sheet-dashboard',
      text: ['COMPRAR', 'RESERVAR'],
    },
    maxPrice: {
      container: 'div[class="current ng-binding"]',
      euroFormat: true,
    },
    outOfStock: {
      container: '#vs-product-sheet-dashboard',
      text: ['Avísame'],
    },
  },
  links: [
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-geforce-gtx-1660-super-dual-oc-6g-evo-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-nvidia-geforce-gtx1660-super-oc-6g-tuf-gaming',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-nvidia-geforce-gtx1660-super-phoenix-oc-6g-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/geforce-gtx-1660-superr-aero-itx-oc-6gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-geforce-gtx-1660s-oc-super-dual-evo-6gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-dual-gtx1660-super-advanced-evo-6g-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-zotac-geforce-rtx-3080-trinity-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-zotac-geforce-rtx-3070-twin-edge-8-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte-geforce-rtx-3080-eagle-oc-10g-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-rog-strix-geforce-rtx-3080-gaming-10g-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtx-3080-gaming-x-trio-10g-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtx-3080-ventus-3x-10g-oc-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-rog-strix-geforce-rtx-3070-gaming-8g-8-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtxr-3070-gaming-x-trio',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte--geforce-rtxr-3070-eagle-oc-8g',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-palit-geforce-rtx-3070-gaming-pro-8-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtx-3070-suprim-x-8gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtx-3080-suprim-x-10g-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-dual-geforce-rtx-3060-ti-8gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-tuf-gaming-geforce-rtx-3060-ti-oc-8gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte--geforce-rtxr-3060-ti-eagle-8g',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte--geforce-rtxr-3060-ti-eagle-oc-8g',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte-geforce-rtxr-3060-ti-master-8g',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte-aorus-geforce-rtx-3070-master-8-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-zotac-gaming-nvidia-geforce-rtxr-3080-trinity-oc-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte-aorus-geforce-rtx-3080-10-gb-gddr6x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-nvidia-geforce-gtx-1660-super-6-gb-gddr6-amp-1',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-geforce-rtx-3060-ti-ventus-2x-ocv1-8gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-dual-gtx1660-super-mini-6-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-rog-strix-geforce-gtx-1660-super-6-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-rog-strix-gtx-1660-super-advanced-edition-6gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-pny-geforce-gtx-1660-super-6-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-dual-geforce-rtx3060ti-mini-oc-edition-8-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/asus-tuf-gaming-nvidia-geforce-rtx-3070-8-gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-zotac-geforce-rtx-3060-twin-edge-12gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-rog-strix-geforce-rtx-3060-gaming-12gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-rog-strix-geforce-rtx-3060-gaming-oc-12gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-tuf-gaming-geforce-rtx-3060-12gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-asus-dual-geforce-rtx-3060-oc-12gb-gddr6',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtx-3060-gaming-x-trio',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-msi-geforce-rtx-3060-gaming-x',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte--geforce-rtxr-3060-eagle-12gb',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte--geforce-rtxr-3060-eagle-oc-12gb',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/tarjeta-grafica-gigabyte-geforce-rtx-3060-gaming-oc-12g',     },
{       brand: 'asus',       model: 'strix',       series: '3080',       url:         'https://www.vsgamers.es/product/geforce-gtx-1660-super-tm-gaming-x-copia',     },
  ],
  name: 'vsgamers',
};
