import {Store} from './store';

export const Wipoid: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '#add_to_cart',
      text: ['COMPRAR'],
    },
    maxPrice: {
      container: '#our_price_display',
      euroFormat: true,
    },
    outOfStock: {
      container: '.buttons_bottom_block no-print',
      text: ['Avísame cuando esté disponible!'],
    },
  },
  links: [
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/evga-geforce-rtx-3090-xc3-ultra-gaming-24gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3080-oc-white-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3080-oc-edition-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3080-amp-holo-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3080-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3080-oc-edition-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3070-oc-white-8gb-gddr6-asus-tuf-gaming-650w-bronze.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3080-trinity-oc-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3080-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3070-oc-white-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3070-oc-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-ekwb-geforce-rtx-3070-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-white-gddr6-asus-tuf-gaming-650w-bronze.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-amp-holo-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3070-oc-edition-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/evga-geforce-rtx-3080-ftw3-gaming-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-white-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/evga-geforce-rtx-3070-xc3-ultra-gaming-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/msi-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-dual-geforce-rtx-3070-oc-edition-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/evga-geforce-rtx-3080-xc3-gaming-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/msi-geforce-rtx-3080-gaming-x-trio-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3080-trinity-10gb-gddr6x.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3060-ti-oc-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-ti-twin-edge-oc-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-twin-edge-oc-12gb-gddr6-asus-tuf-gaming-650w-bronze.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3060-ti-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3060-oc-edition-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-amp-white-edition-12gb-gddr6-asus-tuf-gaming-650w-bronze.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-ti-twin-edge-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3060-ti-oc-edition-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3060-oc-edition-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-8gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-twin-edge-oc-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-dual-geforce-rtx-3060-oc-edition-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-amp-white-edition-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-dual-geforce-rtx-3060-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-twin-edge-12gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-gtx-1660-super-twin-fan-6gb-gddr6-asus-tuf-gaming-650w-bronze.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-rog-strix-geforce-gtx-1660-super-oc-edition-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-gtx-1660-super-amp-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-gtx-1660-super-oc-edition-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-gtx-1660-super-twin-fan-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-tuf-gaming-geforce-gtx-1660-super-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-dual-geforce-gtx-1660-super-mini-oc-edition-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-dual-geforce-gtx-1660-super-evo-oc-edition-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/zotac-gaming-geforce-gtx-1660-twin-fan-6gb-gddr5.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-phoenix-geforce-gtx-1660-super-oc-6gb-gddr6.html',     },
{       brand: 'asus',       model: 'tuf',       series: '3090',       url:         'https://www.wipoid.com/asus-phoenix-geforce-gtx-1660-super-6gb-gddr5.html',     },
  ],
  name: 'wipoid',
};
